import {Hand,Pointer,Scan,Maximize,Minimize,RotateCcw,Camera,CameraOff,Orbit,MoveUpRight} from 'lucide-react';
import {HAND_CONNECTIONS} from '../utils/gestureMath';
const names={NONE:'AWAITING HAND',PALM:'OPEN PALM',BACKHAND:'BACK OF HAND',PINCH:'PINCH',FIST:'CLOSED FIST',VICTORY:'VICTORY',METEOR:'THREE FINGERS'};
const instructions={NONE:'SHOW ONE OPEN PALM TO BEGIN',PALM:'ROTATION CONTROL · MOVE YOUR HAND',BACKHAND:'BACK OF HAND · SWIPE LEFT / RIGHT · CHANGE CITY',PINCH:'ZOOM CONTROL · MOVE HAND FORWARD / BACK',FIST:'PAUSED · OPEN PALM TO RESUME',VICTORY:'RESETTING TO DEFAULT VIEW',METEOR:'3 FINGERS UP · PINKY DOWN · HOLD 0.25 S'};
const diagram=[[47,132],[32,110],[21,89],[12,77],[8,62],[35,74],[29,49],[26,30],[23,15],[49,68],[46,40],[44,20],[43,5],[62,70],[64,44],[65,26],[66,12],[75,78],[83,59],[86,43],[88,30]];
function HandDiagram({tracking}){return <div className={`hand-diagram ${tracking?'detected':''}`}><span className="corner tl"/><span className="corner tr"/><span className="corner bl"/><span className="corner br"/><svg viewBox="0 0 100 145" aria-hidden="true">{HAND_CONNECTIONS.map(([a,b],i)=><line key={i} x1={diagram[a][0]} y1={diagram[a][1]} x2={diagram[b][0]} y2={diagram[b][1]}/>)}{diagram.map(([x,y],i)=><circle key={i} cx={x} cy={y} r="1.6"/>)}<path d="M35 74L62 70L47 132M49 68L75 78L32 110M35 74L75 78" fill="none" strokeOpacity=".25"/></svg><div className="scan-line"/></div>}
export default function HUD({tracking,telemetry,debug,setDebug,fullscreen,onFullscreen,onReset,focusedLocation,error}){
 const s=tracking.status,connected=s.camera==='CONNECTED';
 const toast=telemetry.visualEvent==='METEOR_SHOWER'?'METEOR EVENT':telemetry.gestureAction;
 const hoveredCity=telemetry.hoveredCity;
 const location=focusedLocation||telemetry.focusedLocation||hoveredCity;
 const locationVisible=telemetry.locationLocked||telemetry.focusIntensity>.025||Boolean(hoveredCity);
 const lat=location?.latitude??-(telemetry.x||0),lng=location?.longitude??(((-(telemetry.y||0)+180)%360+360)%360-180);
 const focusColor=location?.accentColor||'#6fffe0';
 const formatCoordinate=(value,positive,negative)=>`${Math.abs(value).toFixed(4)}° ${value>=0?positive:negative}`;
 return <>
 <header><a className="brand" href="/" aria-label="ORBIT home"><Orbit className="brand-icon" strokeWidth={.8}/><div><h1>ORBIT</h1><span>GESTURE CONTROLLED EXPLORER</span></div></a><div className="header-actions"><span className={`live-label ${telemetry.autopilot?'autopilot-mode':''}`}><i/>{telemetry.autopilot?'AUTOPILOT MODE':'INTERACTIVE EARTH'}</span><button className={debug?'active':''} onClick={()=>setDebug(v=>!v)} aria-pressed={debug}><Scan size={15}/> <span>DEBUG MODE</span></button><button onClick={onFullscreen}>{fullscreen?<Minimize size={15}/>:<Maximize size={15}/>}<span>{fullscreen?'EXIT FULLSCREEN':'FULLSCREEN'}</span></button></div></header>
 <aside className="hud left-hud"><div className="rail-title"><span>HAND TRACKING</span><span className="panel-number">01</span></div><div className={`tracking-status ${s.tracking?'is-tracking':''}`}><i/>{s.tracking?'TRACKING':'STANDBY'}</div>
 <div className="field"><label>CAMERA STATUS</label><div className={connected?'accent':''}><i className={`status-dot ${connected?'on':''}`}/>{s.camera}</div></div>
 <div className="field gesture-field"><label>CURRENT GESTURE</label><div key={s.gesture} className={`gesture-readout gesture-${s.gesture.toLowerCase()}`}><i/><strong>{names[s.gesture]}</strong></div><small className="gesture-instruction">{instructions[s.gesture]}</small></div>
 <div className="field confidence" title="MediaPipe handedness classification score. The API does not expose a separate landmark confidence score."><label>TRACKING CONFIDENCE <span>{s.tracking?`${Math.round(s.confidence*100)}%`:'—'}</span></label><div className="meter"><span style={{transform:`scaleX(${s.tracking?s.confidence:0})`}}/></div><small>HANDEDNESS SCORE</small></div>
 <HandDiagram tracking={s.tracking}/><div className="hand-caption">{s.tracking?'HAND LANDMARKS DETECTED':'HOLD ONE HAND IN FRAME'}<br/><span>PALM FORWARD · 21 LANDMARKS</span></div>
 <button className="camera-control" onClick={connected?tracking.toggle:tracking.retry}>{connected?<CameraOff size={13}/>:<Camera size={13}/>} {connected?'DISABLE CAMERA':s.camera==='REQUESTING'||s.camera==='LOADING MODEL'?'RETRY CAMERA':'ENABLE CAMERA'}</button>
 </aside>
 <aside className="hud right-hud"><div className="rail-title"><span>VIEW TELEMETRY</span><span className="panel-number">02</span></div><div className="telemetry-fields"><div><label>LATITUDE</label><b>{Math.abs(lat).toFixed(2)}<small>° {lat>=0?'N':'S'}</small></b></div><div><label>LONGITUDE</label><b>{Math.abs(lng).toFixed(2)}<small>° {lng>=0?'E':'W'}</small></b></div><div className="rotation-field"><label>ROTATION</label><span><b><em>X</em>{(telemetry.x||0).toFixed(1)}°</b><b><em>Y</em>{(telemetry.y||0).toFixed(1)}°</b><b><em>Z</em>{(telemetry.z||0).toFixed(1)}°</b></span></div><div><label>ZOOM</label><b className="accent">{telemetry.zoom.toFixed(2)}<small>×</small></b></div></div><div className="compass"><span className="north">N</span><span className="east">E</span><span className="south">S</span><span className="west">W</span><div className="compass-circle"><span style={{transform:`rotate(${-telemetry.y}deg)`}}/><i/></div></div><button className="reset-button" onClick={onReset}><RotateCcw size={13}/> RESET VIEW <kbd>R</kbd></button><div className="telemetry-note">A WORLD IN MOTION.<br/><span>A NEW PERSPECTIVE.</span></div></aside>
 <section className={`focus-announcement ${locationVisible?'is-visible':''}`} style={{'--focus-accent':focusColor}} aria-live="polite" aria-atomic="true"><div className="focus-city-name">{location?.name||'CITY FOCUS'}</div><div className="focus-coordinates">{location?`${formatCoordinate(location.latitude,'N','S')}  /  ${formatCoordinate(location.longitude,'E','W')}`:'SELECT A NETWORK NODE'}</div><div className="focus-node-status"><i/> {telemetry.locationLocked?'LOCATION LOCKED':hoveredCity&&!telemetry.focusedLocation?'NETWORK NODE':'NODE ACTIVE'}</div></section>
 <div className={`gesture-toast ${toast?'visible':''}`} aria-live="polite">{toast}</div>
 <div className="globe-reticle" aria-hidden="true"><span className="reticle-top">90° N<b>+</b></span><span className="reticle-bottom"><b>+</b>90° S</span><span className="reticle-left">90° W <b>+</b></span><span className="reticle-right"><b>+</b> 90° E</span></div>
 <footer><div><i className="status-dot on"/><span>ORBIT <em>v1.0</em></span><span className="footer-divider"/><span>WEBGL</span><span className="footer-divider"/><span>{connected?'VISION ONLINE':'MOUSE FALLBACK'}</span></div><span className="footer-center">CAMERA INPUT STAYS ON YOUR DEVICE</span><span className="footer-right">A MORE CONNECTED PLANET <MoveUpRight size={12}/></span></footer>
 </>
}
